### ISSUE TITLE
frida.ProcessNotRespondingError: process with pid 4300 either refused to load frida-agent, or terminated during injection

### ISSUE THREAD

**Issue by trueToastedCode** [NyaMisty/actions-iTunes-header#2]
```
C:\Users\lennard>python "C:\Users\lennard\actions-iTunes-header\workflow_helper\iTunesDownload\get_header.py"
Traceback (most recent call last):
  File "C:\Users\lennard\actions-iTunes-header\workflow_helper\iTunesDownload\get_header.py", line 67, in <module>
    session = frida.attach(procName)
  File "C:\Users\lennard\AppData\Local\Programs\Python\Python38\lib\site-packages\frida\__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
  File "C:\Users\lennard\AppData\Local\Programs\Python\Python38\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\lennard\AppData\Local\Programs\Python\Python38\lib\site-packages\frida\core.py", line 994, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
frida.ProcessNotRespondingError: process with pid 4300 either refused to load frida-agent, or terminated during injection
```

**Comment by Yakov5776** [comment]
Should be fixed now
